echo "============================================="
echo "000_Do_Nothing.asm"
echo "---------------------------------------------"
sjasmplus 000_Do_Nothing.asm
echo "============================================="
echo "001_Print_Your_Name.asm"
echo "---------------------------------------------"
sjasmplus 001_Print_Your_Name.asm
echo "============================================="
echo "002_Print_Your_Name_In_Custom_Font.asm"
echo "---------------------------------------------"
sjasmplus 002_Print_Your_Name_In_Custom_Font.asm
echo "============================================="
echo "003_Print_A_Few_Lines_Of_Text.asm"
echo "---------------------------------------------"
sjasmplus 003_Print_A_Few_Lines_Of_Text.asm
echo "============================================="
echo "004_Print_At.asm"
echo "---------------------------------------------"
sjasmplus 004_Print_At.asm
echo "============================================="
echo "005_Print_A_Few_Lines_Of_Text_In_Shadow.asm"
echo "---------------------------------------------"
sjasmplus 005_Print_A_Few_Lines_Of_Text_In_Shadow.asm
echo "============================================="
echo "005_Print_Decimal_Numbers.asm"
echo "---------------------------------------------"
sjasmplus 006_Print_Decimal_Numbers.asm
echo "============================================="
echo "006_Print_Character.asm"
echo "---------------------------------------------"
sjasmplus 007_Print_Character.asm
echo "============================================="
echo "010_Moving_Asterisk.asm"
echo "---------------------------------------------"
sjasmplus 010_Moving_Asterisk.asm
echo "============================================="
echo "011_Moving_Monster.asm"
echo "---------------------------------------------"
sjasmplus 011_Moving_Monster.asm
echo "============================================="
echo "020_Read_All_Keys_And_Print_Key_Codes.asm"
echo "---------------------------------------------"
sjasmplus 020_Read_All_Keys_And_Print_Key_Codes.asm
echo "============================================="
echo "021_Define_Keys_Old.asm"
echo "---------------------------------------------"
sjasmplus 021_Define_Keys_Old.asm
echo "============================================="
echo "022_Define_Keys_Old.asm"
echo "---------------------------------------------"
sjasmplus 022_Define_Keys_Old.asm
echo "============================================="
echo "023_Define_Keys_Newer.asm"
echo "---------------------------------------------"
sjasmplus 023_Define_Keys_Newer.asm
echo "============================================="
echo "030_Merge_Grid.asm"
echo "---------------------------------------------"
sjasmplus 030_Merge_Grid.asm
echo "============================================="
echo "031_Print_Register_Contents.asm"
echo "---------------------------------------------"
sjasmplus 031_Print_Register_Contents.asm
echo "============================================="
echo "032_Memory_Browser.asm"
echo "---------------------------------------------"
sjasmplus 032_Memory_Browser.asm
echo "============================================="
echo "040_Dawn_Of_Sprites.asm"
echo "---------------------------------------------"
sjasmplus 040_Dawn_Of_Sprites.asm
echo "============================================="
echo "050_Game_Framework.asm"
echo "---------------------------------------------"
sjasmplus 050_Game_Framework.asm
