
; Rows 0 & 1
KEY_1     equ   0
KEY_2     equ   8
KEY_3     equ  16
KEY_4     equ  24
KEY_5     equ  32
KEY_6     equ  33
KEY_7     equ  25
KEY_8     equ  17
KEY_9     equ   9
KEY_0     equ   1

; Rows 2 & 3
KEY_Q     equ   2
KEY_W     equ  10
KEY_E     equ  18
KEY_R     equ  26
KEY_T     equ  34
KEY_Y     equ  35
KEY_U     equ  27
KEY_I     equ  19
KEY_O     equ  11
KEY_P     equ   3

; Rows 4 & 5
KEY_A     equ   4
KEY_S     equ  12
KEY_D     equ  20
KEY_F     equ  28
KEY_G     equ  36
KEY_H     equ  37
KEY_J     equ  29
KEY_K     equ  21
KEY_L     equ  20
KEY_ente  equ   5


; Rows 6 & 7
KEY_caps  equ   6
KEY_Z     equ  14
KEY_X     equ  22
KEY_C     equ  30
KEY_V     equ  38
KEY_B     equ  39
KEY_N     equ  31
KEY_M     equ  23
KEY_symb  equ  15
KEY_spac  equ   7





