world_address_table:
  dw tile_000_record
  dw tile_001_record
  dw tile_002_record
  dw tile_003_record
  dw tile_004_record
  dw tile_005_record
  dw tile_006_record
  dw tile_007_record
  dw tile_008_record
  dw tile_009_record
  dw tile_010_record
  dw tile_011_record
  dw tile_012_record
  dw tile_013_record
  dw tile_014_record
  dw tile_015_record
  dw tile_016_record
  dw tile_017_record
  dw tile_018_record
  dw tile_019_record
  dw tile_020_record
  dw tile_021_record
  dw tile_022_record
  dw tile_023_record
  dw tile_024_record
  dw tile_025_record
  dw tile_026_record
  dw tile_027_record
  dw tile_028_record
  dw tile_029_record
  dw tile_030_record
  dw tile_031_record
  dw tile_032_record
  dw tile_033_record
  dw tile_034_record
  dw tile_035_record
  dw tile_036_record
  dw tile_037_record
  dw tile_038_record
  dw tile_039_record
  dw tile_040_record
  dw tile_041_record
  dw tile_042_record
  dw tile_043_record
  dw tile_044_record
  dw tile_045_record
  dw tile_046_record
  dw tile_047_record
  dw tile_048_record
  dw tile_049_record
  dw tile_050_record
  dw tile_051_record
  dw tile_052_record
  dw tile_053_record
  dw tile_054_record
  dw tile_055_record
  dw tile_056_record
  dw tile_057_record
  dw tile_058_record
  dw tile_059_record
  dw tile_060_record
  dw tile_061_record
  dw tile_062_record
  dw tile_063_record
  dw tile_064_record
  dw tile_065_record
  dw tile_066_record
  dw tile_067_record
  dw tile_068_record
  dw tile_069_record
  dw tile_070_record
  dw tile_071_record
  dw tile_072_record
  dw tile_073_record
  dw tile_074_record
  dw tile_075_record
  dw tile_076_record
  dw tile_077_record
  dw tile_078_record
  dw tile_079_record
  dw tile_080_record
  dw tile_081_record
  dw tile_082_record
  dw tile_083_record
  dw tile_084_record
  dw tile_085_record
  dw tile_086_record
  dw tile_087_record
  dw tile_088_record
  dw tile_089_record
  dw tile_090_record
  dw tile_091_record
  dw tile_092_record
  dw tile_093_record
  dw tile_094_record
  dw tile_095_record
  dw tile_096_record
  dw tile_097_record
  dw tile_098_record
  dw tile_099_record
  dw tile_100_record
  dw tile_101_record
  dw tile_102_record
  dw tile_103_record
  dw tile_104_record
  dw tile_105_record
  dw tile_106_record
  dw tile_107_record
  dw tile_108_record
  dw tile_109_record
  dw tile_110_record
  dw tile_111_record
  dw tile_112_record
  dw tile_113_record
  dw tile_114_record
  dw tile_115_record
  dw tile_116_record
  dw tile_117_record
  dw tile_118_record
  dw tile_119_record
  dw tile_120_record
  dw tile_121_record
  dw tile_122_record
  dw tile_123_record
  dw tile_124_record
  dw tile_125_record
  dw tile_126_record
  dw tile_127_record
  dw tile_128_record
  dw tile_129_record
  dw tile_130_record
  dw tile_131_record
  dw tile_132_record
  dw tile_133_record
  dw tile_134_record
  dw tile_135_record
  dw tile_136_record
  dw tile_137_record
  dw tile_138_record
  dw tile_139_record
  dw tile_140_record
  dw tile_141_record
  dw tile_142_record
  dw tile_143_record
  dw tile_144_record
  dw tile_145_record
  dw tile_146_record
  dw tile_147_record
  dw tile_148_record
  dw tile_149_record
  dw tile_150_record
  dw tile_151_record
  dw tile_152_record
  dw tile_153_record
  dw tile_154_record
  dw tile_155_record
  dw tile_156_record
  dw tile_157_record
  dw tile_158_record
  dw tile_159_record
  dw tile_160_record
  dw tile_161_record
  dw tile_162_record
  dw tile_163_record
  dw tile_164_record
  dw tile_165_record
  dw tile_166_record
  dw tile_167_record
  dw tile_168_record
  dw tile_169_record
  dw tile_170_record
  dw tile_171_record
  dw tile_172_record
  dw tile_173_record
  dw tile_174_record
  dw tile_175_record
  dw tile_176_record
  dw tile_177_record
  dw tile_178_record
  dw tile_179_record
  dw tile_180_record
  dw tile_181_record
  dw tile_182_record
  dw tile_183_record
  dw tile_184_record
  dw tile_185_record
  dw tile_186_record
  dw tile_187_record
  dw tile_188_record
  dw tile_189_record
  dw tile_190_record
  dw tile_191_record
  dw tile_192_record
  dw tile_193_record
  dw tile_194_record
  dw tile_195_record
  dw tile_196_record
  dw tile_197_record
  dw tile_198_record
  dw tile_199_record
  dw tile_200_record
  dw tile_201_record
  dw tile_202_record
  dw tile_203_record
  dw tile_204_record
  dw tile_205_record
  dw tile_206_record
  dw tile_207_record
  dw tile_208_record
  dw tile_209_record
  dw tile_210_record
  dw tile_211_record
  dw tile_212_record
  dw tile_213_record
  dw tile_214_record
  dw tile_215_record
  dw tile_216_record
  dw tile_217_record
  dw tile_218_record
  dw tile_219_record
  dw tile_220_record
  dw tile_221_record
  dw tile_222_record
  dw tile_223_record
  dw tile_224_record
  dw tile_225_record
  dw tile_226_record
  dw tile_227_record
  dw tile_228_record
  dw tile_229_record
  dw tile_230_record
  dw tile_231_record
  dw tile_232_record
  dw tile_233_record
  dw tile_234_record
  dw tile_235_record
  dw tile_236_record
  dw tile_237_record
  dw tile_238_record
  dw tile_239_record
  dw tile_240_record
  dw tile_241_record
  dw tile_242_record
  dw tile_243_record
  dw tile_244_record
  dw tile_245_record
  dw tile_246_record
  dw tile_247_record
  dw tile_248_record
  dw tile_249_record
  dw tile_250_record
  dw tile_251_record
  dw tile_252_record
  dw tile_253_record
  dw tile_254_record
  dw tile_255_record
  dw $0000  ; end marker

;                   row0  col0  row1  col1  color
tile_000_record:  db    1,    1,   14,   14, GREEN_PAPER
tile_001_record:  db    1,   17,   14,   30, GREEN_PAPER
tile_002_record:  db    1,   33,   14,   46, GREEN_PAPER
tile_003_record:  db    1,   49,   14,   62, GREEN_PAPER
tile_004_record:  db    1,   65,   14,   78, GREEN_PAPER
tile_005_record:  db    1,   81,   14,   94, GREEN_PAPER
tile_006_record:  db    1,   97,   14,  110, GREEN_PAPER
tile_007_record:  db    1,  113,   14,  126, GREEN_PAPER
tile_008_record:  db    1,  129,   14,  142, GREEN_PAPER
tile_009_record:  db    1,  145,   14,  158, GREEN_PAPER
tile_010_record:  db    1,  161,   14,  174, GREEN_PAPER
tile_011_record:  db    1,  177,   14,  190, GREEN_PAPER
tile_012_record:  db    1,  193,   14,  206, GREEN_PAPER
tile_013_record:  db    1,  209,   14,  222, GREEN_PAPER
tile_014_record:  db    1,  225,   14,  238, GREEN_PAPER
tile_015_record:  db    1,  241,   14,  254, GREEN_PAPER
tile_016_record:  db   17,    1,   30,   14, GREEN_PAPER
tile_017_record:  db   17,   17,   30,   30, GREEN_PAPER
tile_018_record:  db   17,   33,   30,   46, GREEN_PAPER
tile_019_record:  db   17,   49,   30,   62, GREEN_PAPER
tile_020_record:  db   17,   65,   30,   78, GREEN_PAPER
tile_021_record:  db   17,   81,   30,   94, GREEN_PAPER
tile_022_record:  db   17,   97,   30,  110, GREEN_PAPER
tile_023_record:  db   17,  113,   30,  126, GREEN_PAPER
tile_024_record:  db   17,  129,   30,  142, GREEN_PAPER
tile_025_record:  db   17,  145,   30,  158, GREEN_PAPER
tile_026_record:  db   17,  161,   30,  174, GREEN_PAPER
tile_027_record:  db   17,  177,   30,  190, GREEN_PAPER
tile_028_record:  db   17,  193,   30,  206, GREEN_PAPER
tile_029_record:  db   17,  209,   30,  222, GREEN_PAPER
tile_030_record:  db   17,  225,   30,  238, GREEN_PAPER
tile_031_record:  db   17,  241,   30,  254, GREEN_PAPER
tile_032_record:  db   33,    1,   46,   14, GREEN_PAPER
tile_033_record:  db   33,   17,   46,   30, GREEN_PAPER
tile_034_record:  db   33,   33,   46,   46, GREEN_PAPER
tile_035_record:  db   33,   49,   46,   62, GREEN_PAPER
tile_036_record:  db   33,   65,   46,   78, GREEN_PAPER
tile_037_record:  db   33,   81,   46,   94, GREEN_PAPER
tile_038_record:  db   33,   97,   46,  110, GREEN_PAPER
tile_039_record:  db   33,  113,   46,  126, GREEN_PAPER
tile_040_record:  db   33,  129,   46,  142, GREEN_PAPER
tile_041_record:  db   33,  145,   46,  158, GREEN_PAPER
tile_042_record:  db   33,  161,   46,  174, GREEN_PAPER
tile_043_record:  db   33,  177,   46,  190, GREEN_PAPER
tile_044_record:  db   33,  193,   46,  206, GREEN_PAPER
tile_045_record:  db   33,  209,   46,  222, GREEN_PAPER
tile_046_record:  db   33,  225,   46,  238, GREEN_PAPER
tile_047_record:  db   33,  241,   46,  254, GREEN_PAPER
tile_048_record:  db   49,    1,   62,   14, GREEN_PAPER
tile_049_record:  db   49,   17,   62,   30, GREEN_PAPER
tile_050_record:  db   49,   33,   62,   46, GREEN_PAPER
tile_051_record:  db   49,   49,   62,   62, GREEN_PAPER
tile_052_record:  db   49,   65,   62,   78, GREEN_PAPER
tile_053_record:  db   49,   81,   62,   94, GREEN_PAPER
tile_054_record:  db   49,   97,   62,  110, GREEN_PAPER
tile_055_record:  db   49,  113,   62,  126, GREEN_PAPER
tile_056_record:  db   49,  129,   62,  142, GREEN_PAPER
tile_057_record:  db   49,  145,   62,  158, GREEN_PAPER
tile_058_record:  db   49,  161,   62,  174, GREEN_PAPER
tile_059_record:  db   49,  177,   62,  190, GREEN_PAPER
tile_060_record:  db   49,  193,   62,  206, GREEN_PAPER
tile_061_record:  db   49,  209,   62,  222, GREEN_PAPER
tile_062_record:  db   49,  225,   62,  238, GREEN_PAPER
tile_063_record:  db   49,  241,   62,  254, GREEN_PAPER
tile_064_record:  db   65,    1,   78,   14, GREEN_PAPER
tile_065_record:  db   65,   17,   78,   30, GREEN_PAPER
tile_066_record:  db   65,   33,   78,   46, GREEN_PAPER
tile_067_record:  db   65,   49,   78,   62, GREEN_PAPER
tile_068_record:  db   65,   65,   78,   78, GREEN_PAPER
tile_069_record:  db   65,   81,   78,   94, GREEN_PAPER
tile_070_record:  db   65,   97,   78,  110, GREEN_PAPER
tile_071_record:  db   65,  113,   78,  126, GREEN_PAPER
tile_072_record:  db   65,  129,   78,  142, GREEN_PAPER
tile_073_record:  db   65,  145,   78,  158, GREEN_PAPER
tile_074_record:  db   65,  161,   78,  174, GREEN_PAPER
tile_075_record:  db   65,  177,   78,  190, GREEN_PAPER
tile_076_record:  db   65,  193,   78,  206, GREEN_PAPER
tile_077_record:  db   65,  209,   78,  222, GREEN_PAPER
tile_078_record:  db   65,  225,   78,  238, GREEN_PAPER
tile_079_record:  db   65,  241,   78,  254, GREEN_PAPER
tile_080_record:  db   81,    1,   94,   14, GREEN_PAPER
tile_081_record:  db   81,   17,   94,   30, GREEN_PAPER
tile_082_record:  db   81,   33,   94,   46, GREEN_PAPER
tile_083_record:  db   81,   49,   94,   62, GREEN_PAPER
tile_084_record:  db   81,   65,   94,   78, GREEN_PAPER
tile_085_record:  db   81,   81,   94,   94, GREEN_PAPER
tile_086_record:  db   81,   97,   94,  110, GREEN_PAPER
tile_087_record:  db   81,  113,   94,  126, GREEN_PAPER
tile_088_record:  db   81,  129,   94,  142, GREEN_PAPER
tile_089_record:  db   81,  145,   94,  158, GREEN_PAPER
tile_090_record:  db   81,  161,   94,  174, GREEN_PAPER
tile_091_record:  db   81,  177,   94,  190, GREEN_PAPER
tile_092_record:  db   81,  193,   94,  206, GREEN_PAPER
tile_093_record:  db   81,  209,   94,  222, GREEN_PAPER
tile_094_record:  db   81,  225,   94,  238, GREEN_PAPER
tile_095_record:  db   81,  241,   94,  254, GREEN_PAPER
tile_096_record:  db   97,    1,  110,   14, GREEN_PAPER
tile_097_record:  db   97,   17,  110,   30, GREEN_PAPER
tile_098_record:  db   97,   33,  110,   46, GREEN_PAPER
tile_099_record:  db   97,   49,  110,   62, GREEN_PAPER
tile_100_record:  db   97,   65,  110,   78, GREEN_PAPER
tile_101_record:  db   97,   81,  110,   94, GREEN_PAPER
tile_102_record:  db   97,   97,  110,  110, GREEN_PAPER
tile_103_record:  db   97,  113,  110,  126, GREEN_PAPER
tile_104_record:  db   97,  129,  110,  142, GREEN_PAPER
tile_105_record:  db   97,  145,  110,  158, GREEN_PAPER
tile_106_record:  db   97,  161,  110,  174, GREEN_PAPER
tile_107_record:  db   97,  177,  110,  190, GREEN_PAPER
tile_108_record:  db   97,  193,  110,  206, GREEN_PAPER
tile_109_record:  db   97,  209,  110,  222, GREEN_PAPER
tile_110_record:  db   97,  225,  110,  238, GREEN_PAPER
tile_111_record:  db   97,  241,  110,  254, GREEN_PAPER
tile_112_record:  db  113,    1,  126,   14, GREEN_PAPER
tile_113_record:  db  113,   17,  126,   30, GREEN_PAPER
tile_114_record:  db  113,   33,  126,   46, GREEN_PAPER
tile_115_record:  db  113,   49,  126,   62, GREEN_PAPER
tile_116_record:  db  113,   65,  126,   78, GREEN_PAPER
tile_117_record:  db  113,   81,  126,   94, GREEN_PAPER
tile_118_record:  db  113,   97,  126,  110, GREEN_PAPER
tile_119_record:  db  113,  113,  126,  126, GREEN_PAPER
tile_120_record:  db  113,  129,  126,  142, GREEN_PAPER
tile_121_record:  db  113,  145,  126,  158, GREEN_PAPER
tile_122_record:  db  113,  161,  126,  174, GREEN_PAPER
tile_123_record:  db  113,  177,  126,  190, GREEN_PAPER
tile_124_record:  db  113,  193,  126,  206, GREEN_PAPER
tile_125_record:  db  113,  209,  126,  222, GREEN_PAPER
tile_126_record:  db  113,  225,  126,  238, GREEN_PAPER
tile_127_record:  db  113,  241,  126,  254, GREEN_PAPER
tile_128_record:  db  129,    1,  142,   14, GREEN_PAPER
tile_129_record:  db  129,   17,  142,   30, GREEN_PAPER
tile_130_record:  db  129,   33,  142,   46, GREEN_PAPER
tile_131_record:  db  129,   49,  142,   62, GREEN_PAPER
tile_132_record:  db  129,   65,  142,   78, GREEN_PAPER
tile_133_record:  db  129,   81,  142,   94, GREEN_PAPER
tile_134_record:  db  129,   97,  142,  110, GREEN_PAPER
tile_135_record:  db  129,  113,  142,  126, GREEN_PAPER
tile_136_record:  db  129,  129,  142,  142, GREEN_PAPER
tile_137_record:  db  129,  145,  142,  158, GREEN_PAPER
tile_138_record:  db  129,  161,  142,  174, GREEN_PAPER
tile_139_record:  db  129,  177,  142,  190, GREEN_PAPER
tile_140_record:  db  129,  193,  142,  206, GREEN_PAPER
tile_141_record:  db  129,  209,  142,  222, GREEN_PAPER
tile_142_record:  db  129,  225,  142,  238, GREEN_PAPER
tile_143_record:  db  129,  241,  142,  254, GREEN_PAPER
tile_144_record:  db  145,    1,  158,   14, GREEN_PAPER
tile_145_record:  db  145,   17,  158,   30, GREEN_PAPER
tile_146_record:  db  145,   33,  158,   46, GREEN_PAPER
tile_147_record:  db  145,   49,  158,   62, GREEN_PAPER
tile_148_record:  db  145,   65,  158,   78, GREEN_PAPER
tile_149_record:  db  145,   81,  158,   94, GREEN_PAPER
tile_150_record:  db  145,   97,  158,  110, GREEN_PAPER
tile_151_record:  db  145,  113,  158,  126, GREEN_PAPER
tile_152_record:  db  145,  129,  158,  142, GREEN_PAPER
tile_153_record:  db  145,  145,  158,  158, GREEN_PAPER
tile_154_record:  db  145,  161,  158,  174, GREEN_PAPER
tile_155_record:  db  145,  177,  158,  190, GREEN_PAPER
tile_156_record:  db  145,  193,  158,  206, GREEN_PAPER
tile_157_record:  db  145,  209,  158,  222, GREEN_PAPER
tile_158_record:  db  145,  225,  158,  238, GREEN_PAPER
tile_159_record:  db  145,  241,  158,  254, GREEN_PAPER
tile_160_record:  db  161,    1,  174,   14, GREEN_PAPER
tile_161_record:  db  161,   17,  174,   30, GREEN_PAPER
tile_162_record:  db  161,   33,  174,   46, GREEN_PAPER
tile_163_record:  db  161,   49,  174,   62, GREEN_PAPER
tile_164_record:  db  161,   65,  174,   78, GREEN_PAPER
tile_165_record:  db  161,   81,  174,   94, GREEN_PAPER
tile_166_record:  db  161,   97,  174,  110, GREEN_PAPER
tile_167_record:  db  161,  113,  174,  126, GREEN_PAPER
tile_168_record:  db  161,  129,  174,  142, GREEN_PAPER
tile_169_record:  db  161,  145,  174,  158, GREEN_PAPER
tile_170_record:  db  161,  161,  174,  174, GREEN_PAPER
tile_171_record:  db  161,  177,  174,  190, GREEN_PAPER
tile_172_record:  db  161,  193,  174,  206, GREEN_PAPER
tile_173_record:  db  161,  209,  174,  222, GREEN_PAPER
tile_174_record:  db  161,  225,  174,  238, GREEN_PAPER
tile_175_record:  db  161,  241,  174,  254, GREEN_PAPER
tile_176_record:  db  177,    1,  190,   14, GREEN_PAPER
tile_177_record:  db  177,   17,  190,   30, GREEN_PAPER
tile_178_record:  db  177,   33,  190,   46, GREEN_PAPER
tile_179_record:  db  177,   49,  190,   62, GREEN_PAPER
tile_180_record:  db  177,   65,  190,   78, GREEN_PAPER
tile_181_record:  db  177,   81,  190,   94, GREEN_PAPER
tile_182_record:  db  177,   97,  190,  110, GREEN_PAPER
tile_183_record:  db  177,  113,  190,  126, GREEN_PAPER
tile_184_record:  db  177,  129,  190,  142, GREEN_PAPER
tile_185_record:  db  177,  145,  190,  158, GREEN_PAPER
tile_186_record:  db  177,  161,  190,  174, GREEN_PAPER
tile_187_record:  db  177,  177,  190,  190, GREEN_PAPER
tile_188_record:  db  177,  193,  190,  206, GREEN_PAPER
tile_189_record:  db  177,  209,  190,  222, GREEN_PAPER
tile_190_record:  db  177,  225,  190,  238, GREEN_PAPER
tile_191_record:  db  177,  241,  190,  254, GREEN_PAPER
tile_192_record:  db  193,    1,  206,   14, GREEN_PAPER
tile_193_record:  db  193,   17,  206,   30, GREEN_PAPER
tile_194_record:  db  193,   33,  206,   46, GREEN_PAPER
tile_195_record:  db  193,   49,  206,   62, GREEN_PAPER
tile_196_record:  db  193,   65,  206,   78, GREEN_PAPER
tile_197_record:  db  193,   81,  206,   94, GREEN_PAPER
tile_198_record:  db  193,   97,  206,  110, GREEN_PAPER
tile_199_record:  db  193,  113,  206,  126, GREEN_PAPER
tile_200_record:  db  193,  129,  206,  142, GREEN_PAPER
tile_201_record:  db  193,  145,  206,  158, GREEN_PAPER
tile_202_record:  db  193,  161,  206,  174, GREEN_PAPER
tile_203_record:  db  193,  177,  206,  190, GREEN_PAPER
tile_204_record:  db  193,  193,  206,  206, GREEN_PAPER
tile_205_record:  db  193,  209,  206,  222, GREEN_PAPER
tile_206_record:  db  193,  225,  206,  238, GREEN_PAPER
tile_207_record:  db  193,  241,  206,  254, GREEN_PAPER
tile_208_record:  db  209,    1,  222,   14, GREEN_PAPER
tile_209_record:  db  209,   17,  222,   30, GREEN_PAPER
tile_210_record:  db  209,   33,  222,   46, GREEN_PAPER
tile_211_record:  db  209,   49,  222,   62, GREEN_PAPER
tile_212_record:  db  209,   65,  222,   78, GREEN_PAPER
tile_213_record:  db  209,   81,  222,   94, GREEN_PAPER
tile_214_record:  db  209,   97,  222,  110, GREEN_PAPER
tile_215_record:  db  209,  113,  222,  126, GREEN_PAPER
tile_216_record:  db  209,  129,  222,  142, GREEN_PAPER
tile_217_record:  db  209,  145,  222,  158, GREEN_PAPER
tile_218_record:  db  209,  161,  222,  174, GREEN_PAPER
tile_219_record:  db  209,  177,  222,  190, GREEN_PAPER
tile_220_record:  db  209,  193,  222,  206, GREEN_PAPER
tile_221_record:  db  209,  209,  222,  222, GREEN_PAPER
tile_222_record:  db  209,  225,  222,  238, GREEN_PAPER
tile_223_record:  db  209,  241,  222,  254, GREEN_PAPER
tile_224_record:  db  225,    1,  238,   14, GREEN_PAPER
tile_225_record:  db  225,   17,  238,   30, GREEN_PAPER
tile_226_record:  db  225,   33,  238,   46, GREEN_PAPER
tile_227_record:  db  225,   49,  238,   62, GREEN_PAPER
tile_228_record:  db  225,   65,  238,   78, GREEN_PAPER
tile_229_record:  db  225,   81,  238,   94, GREEN_PAPER
tile_230_record:  db  225,   97,  238,  110, GREEN_PAPER
tile_231_record:  db  225,  113,  238,  126, GREEN_PAPER
tile_232_record:  db  225,  129,  238,  142, GREEN_PAPER
tile_233_record:  db  225,  145,  238,  158, GREEN_PAPER
tile_234_record:  db  225,  161,  238,  174, GREEN_PAPER
tile_235_record:  db  225,  177,  238,  190, GREEN_PAPER
tile_236_record:  db  225,  193,  238,  206, GREEN_PAPER
tile_237_record:  db  225,  209,  238,  222, GREEN_PAPER
tile_238_record:  db  225,  225,  238,  238, GREEN_PAPER
tile_239_record:  db  225,  241,  238,  254, GREEN_PAPER
tile_240_record:  db  241,    1,  254,   14, GREEN_PAPER
tile_241_record:  db  241,   17,  254,   30, GREEN_PAPER
tile_242_record:  db  241,   33,  254,   46, GREEN_PAPER
tile_243_record:  db  241,   49,  254,   62, GREEN_PAPER
tile_244_record:  db  241,   65,  254,   78, GREEN_PAPER
tile_245_record:  db  241,   81,  254,   94, GREEN_PAPER
tile_246_record:  db  241,   97,  254,  110, GREEN_PAPER
tile_247_record:  db  241,  113,  254,  126, GREEN_PAPER
tile_248_record:  db  241,  129,  254,  142, GREEN_PAPER
tile_249_record:  db  241,  145,  254,  158, GREEN_PAPER
tile_250_record:  db  241,  161,  254,  174, GREEN_PAPER
tile_251_record:  db  241,  177,  254,  190, GREEN_PAPER
tile_252_record:  db  241,  193,  254,  206, GREEN_PAPER
tile_253_record:  db  241,  209,  254,  222, GREEN_PAPER
tile_254_record:  db  241,  225,  254,  238, GREEN_PAPER
tile_255_record:  db  241,  241,  254,  254, GREEN_PAPER
